---
- name: Create directory for the update check script
  ansible.builtin.file:
    path: /usr/local/libexec
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Install update check script
  ansible.builtin.template:
    src: update-available.j2
    dest: "/usr/local/libexec/{{ lgsm_server }}-update-available"
    mode: '0755'
    owner: root
    group: root

- name: Install gameserver update systemd units
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/{{ lgsm_server }}-update.{{ item.type }}"
    mode: '0644'
    owner: root
    group: root
  loop:
    - { src: systemd-update-unit.j2, type: service }
    - { src: systemd-update-timer.j2, type: timer }

- name: Enable and start gameserver update timer
  ansible.builtin.systemd:
    name: "{{ lgsm_server }}-update.timer"
    state: started
    enabled: true
    daemon_reload: true
